### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by endymion** [dorack/jiralicious#38]
This gem can't even find an issue in JIRA.  Has it been abandoned?

**Comment by dorack** [comment]
No it has not been abandoned but you need to use the correct distribution. Some information would be helpful.

1. JIRA Version?
2. Ruby Version?
3. Jiralicious Version?
4. What errors are you receiving?

**Comment by jufemaiz** [comment]
Latest commit 2014. Two open PRs.

Can you confirm this is a non-abandoned project?

**Comment by shortdudey123** [comment]
Added another PR to the list :)

**Comment by dorack** [comment]
The project is not abandoned but it is for the most part complete in the consumption of the JIRA API. So unless the API changes it's minor tweaks which I rely on the other uses to assist with since I have not had any issues for anything I have used the gem for.
