### ISSUE TITLE
Cannot create issues

### ISSUE THREAD

**Issue by sagarjauhari** [dorack/jiralicious#39]
I'm getting the error

```
"errors"=>{"project"=>"project is required"}
```

Even though I have tried using the key or id in the hash

<pre>
hash = {
    "reporter" => { "name" => ENV["JIRA_USERNAME"] }, 
     "summary" => "test create", 
     # "project" => { "key"=> "CLA" }, 
     "project" => { "id"=> 1099 }, 
     "issuetype" => { "name"=> "Improvement" }
   }
  issue = Jiralicious::Issue.new(hash)
  issue.save!
</pre>

**Comment by dorack** [comment]
What does your config look like? The project by default is set in the config block or the yml.

**Comment by sagarjauhari** [comment]
In the wiki, it says
> The intial configuration is assumed to be completed and the project preselected.

What does preselected mean here? Just passing the Key/Id in the hash?

**Comment by sagarjauhari** [comment]
Ah, my config block did not have the project key/value pair

**Comment by sagarjauhari** [comment]
What is the way to provide project information in the config? I tried a hash/url/key/id but doesn't seem to work and can't find an example.

**Comment by dorack** [comment]
Here is the wiki but it may be out of date. I'll look at it tonight. https://github.com/dorack/jiralicious/wiki/Jiralicious::Issue-Creation

**Comment by zenvdeluca** [comment]
I am having the same issue here.

Jiralicious::TransitionError: #<HTTParty::Response:0x7fa60d1b6df8 parsed_response={"errorMessages"=>[], "errors"=>{"project"=>"project is required"}},

**Comment by asafg** [comment]
sagarjauhari, zenvdeluca, did any of you solve the problem?
I am facing the same error message.

**Comment by dorack** [comment]
closing issue as resolved via built in process that handles the edge case.
