### ISSUE TITLE
Highchart shows xAxis label from drilldown on drillup.

### ISSUE THREAD

**Issue by prachi3119** [dorack/jiralicious#40]
When I click on district it shows villages on drilldown but when i drillup it shows xAxis data  along with labels from drilldown i.e. village name with District name. Here is the fiddle - http://jsfiddle.net/prachi_chandra/3e4Lnctm/3/
Also can I hide the xAxis series showing as 1, 2 ,3 ,4 ,5  if there is no more district name.

I would really appreciate if somebody could help me fix this. Thanks in advance.

**Comment by shortdudey123** [comment]
Spam? or wrong github project?

**Comment by dorack** [comment]
closing since it is not valid
